/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poo;


import com.entropyinteractive.*;  //jgame
import poo.Enemigos.AvionHostil;
import poo.Enemigos.AvionRojo;
import poo.Enemigos.GrupoAvionesRojos;

import java.awt.*;
import java.awt.event.*; //eventos

import java.awt.image.*;  //imagenes
import javax.imageio.*; //imagenes

import java.awt.Graphics2D;

import java.util.LinkedList;

import java.util.*;
import java.text.*;

 


public class Juego1943 extends JGame {

	Date dInit = new Date();
	Date dAhora;
	SimpleDateFormat ft = new SimpleDateFormat ("mm:ss");
	final double NAVE_DESPLAZAMIENTO=150.0;

    BufferedImage img_fondo = null;
    
    P38 heroe = new P38();
    AvionHostil avion = new AvionHostil();
    GrupoAvionesRojos avionesrojos = new GrupoAvionesRojos();

    public Juego1943() {

        super("1943: The Battle of Midway", 800, 600);
        //System.out.println(appProperties.stringPropertyNames());
    }

    public void gameStartup() {
		System.out.println("gameStartup");
        try{
			img_fondo= ImageIO.read(getClass().getClassLoader().getResourceAsStream("img/fondojuego.jpg"));

            heroe.setPosicion(getWidth() / 2,getHeight() / 2 );
            avion.setPosicion(getWidth() / 2,50);
        }
        catch(Exception e){
			System.out.println(e);
        }
       
    }

    public void gameUpdate(double delta) {
        Keyboard keyboard = this.getKeyboard();

        // Procesar teclas de direccion
        if (keyboard.isKeyPressed(KeyEvent.VK_UP)) {
            heroe.setY(heroe.getY() - NAVE_DESPLAZAMIENTO * delta);
        }

        if (keyboard.isKeyPressed(KeyEvent.VK_DOWN)) {
            heroe.setY(heroe.getY() + NAVE_DESPLAZAMIENTO * delta);
        }

        if (keyboard.isKeyPressed(KeyEvent.VK_LEFT)) {
            heroe.setX(heroe.getX() - NAVE_DESPLAZAMIENTO * delta);
        }

        if (keyboard.isKeyPressed(KeyEvent.VK_RIGHT)) {
            heroe.setX(heroe.getX() + NAVE_DESPLAZAMIENTO * delta);
        }

        // Esc fin del juego
        LinkedList<KeyEvent> keyEvents = keyboard.getEvents();
        for (KeyEvent event : keyEvents) {
            if ((event.getID() == KeyEvent.KEY_PRESSED) &&
                    (event.getKeyCode() == KeyEvent.VK_ESCAPE)) {
                stop();
            }
        }

        heroe.moverse();
        avion.moverse();
        for (AvionRojo avionrojo : avionesrojos.getAviones()) {
            avionrojo.moverse();
        }
    }
    public void gameDraw(Graphics2D g) {

    	dAhora= new Date( );
    	long dateDiff = dAhora.getTime() - dInit.getTime();
    	long diffSeconds = dateDiff / 1000 % 60;
		long diffMinutes = dateDiff / (60 * 1000) % 60;


        g.drawImage(img_fondo,0,0,null);// imagen de fondo

        g.setColor(Color.black);
        g.drawString("Tiempo de Juego: "+diffMinutes+":"+diffSeconds,12,42);
        g.drawString("Tecla ESC = Fin del Juego ",592,42);

    	g.setColor(Color.white);
    	g.drawString("Tiempo de Juego: "+diffMinutes+":"+diffSeconds,10,40);
		g.drawString("Tecla ESC = Fin del Juego ",590,40);

        
        heroe.draw(g);
        avion.draw(g);
        for(AvionRojo avionrojo: avionesrojos.getAviones())
            avionrojo.draw(g);
    }

    public void gameShutdown() {
       Log.info(getClass().getSimpleName(), "Shutting down game");
    }
}